### ISSUE TITLE
Testing issue-posting feature

### ISSUE THREAD

**Issue by le000255** [le000255/grid-layout-with-flex-components#1]
Hi @abhaysharma,
I would like to send you a test issue to see if it works properly.
On top of that, I would like to ask if this week assignment repo name needs changing into 'mtm6201-week2' to match with the style of the last submission. The current forked repo name that I have is from your original name which is 'grid-layout-with-flex-components'.

Please let me know if there is any change needed. 
Thank you so much!

Eddie - Gia Thinh Le

**Comment by abhaysharma** [comment]
@le000255  the issue is working fine and I got the notification.
No, the repository name does not need to be changed.
